var profile = [{
    000001: [{Name="Jericho"},{likes = ["Pizza","Bikes","Sewing","Cooking","Weights"]}],
    000002: [{Name="Hamish"},{likes = ["Games","Pool","Swimming","Cars","Cats"]}],
    000003: [{Name="Jack"},{likes = ["Movies","Music","Pickling","Sewing","Art"]}],
    000004: [{Name="Sarah"},{likes = ["Clubs","Pizza","Cats","Traveling","Bikes"]}],
    000005: [{Name="Ben"},{likes = ["","Swimming","Reading","Weights","Pizza"]}],
    000006: [{Name="Dalton"},{likes = ["Bikes","","Swimming","Cooking","Youtube"]}],
    000007: [{Name="Andrew"},{likes = ["Cooking","Clothes","Cats","Bikes","Landscaping"]}],
    000011: [{Name="Helen"},{likes = ["Drinking","Traveling","Pizza","Games","Reading"]}],
    000012: [{Name="Achilles"},{likes = ["Art","Swimming","Clothes","Coffee","Sewing"]}],
    000013: [{Name="Roger"},{likes = ["Movies","Cooking","Youtube","Music","Bikes"]}],
    000014: [{Name="Stan"},{likes = ["Cats","Pizza","","Bikes","Art"]}],
    000015: [{Name="Steve"},{likes = ["Pizza","Bikes","Games","Traveling","Movies"]}],
    000016: [{Name="Mandy"},{likes = ["Clubs","","Weights","Cats","Art"]}],
    000017: [{Name="Juan"},{likes = ["Sewing","Clothes","Art","Swimming","Wine"]}],
    000020: [{Name="Casper"},{likes = ["Drinking","Bikes","Movies","Pizza","Games"]}],
    000021: [{Name="Arthur"},{likes = ["","Games","Cars","Drinking","Cooking"]}],
    000022: [{Name="Samuel"},{likes = ["Music","Nights In","Swimming","Clubs","Movies"]}],
    000023: [{Name="Augustus"},{likes = ["Traveling","Cooking","Art","Pizza","Clothes"]}],
    000024: [{Name="Louise"},{likes = ["Shoes","Swimming","Music","Sewing","Drinker"]}],
    000025: [{Name="Riley"},{likes = ["Bikes","Cars","Pizza","Weights","Coffee"]}],
    000026: [{Name="Connie"},{likes = ["Weights","Games","Reading","Cars","Pizza"]}],
}]
console.log(likes[1].likes);